# Generated by Django 4.0.5 on 2022-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('receipt_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='единица измерения')),
                ('vendor_name', models.CharField(max_length=250, verbose_name='имя поставщика')),
            ],
        ),
    ]
