# Generated by Django 3.2.9 on 2022-06-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='receipt_date',
            field=models.DateTimeField(verbose_name='дата поступления'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=250)),
                ('new_model', models.ManyToManyField(to='shop.Warehouse')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=250)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.warehouse')),
            ],
        ),
    ]
