# Generated by Django 3.2.9 on 2022-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_warehouse_receipt_date_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=250)),
                ('new_model', models.ManyToManyField(to='shop.Warehouse')),
            ],
        ),
    ]
